### ISSUE TITLE
Error when installing on MAC

### ISSUE THREAD

**Issue by rackpointltd** [surfow/exchanger#1]
https://monosnap.com/file/59TJt7lK8RTM36eLeFSL5HbGtrpEHf

Please see the attached screenshot of the error I have.

**Comment by rackpointltd** [comment]
Process:               Exchanger [33705]
Path:                  /private/var/folders/*/Exchanger.app/Contents/MacOS/Exchanger
Identifier:            com.electron.exchanger
Version:               1.0.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Exchanger [33705]
User ID:               501

Date/Time:             2018-10-13 18:02:46.040 +0100
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Anonymous UUID:        04FE0C77-E144-44B8-3DBD-A1A0B8C0D914

Sleep/Wake UUID:       8885EE4A-6036-40B3-B2D4-419BEC21031A

Time Awake Since Boot: 250000 seconds
Time Since Wake:       1800 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /private/var/folders/*/Exchanger.app/Contents/MacOS/Exchanger
  Reason: no suitable image found.  Did find:
	/private/var/folders/62/3hgy6yr57zz90gmz0w3gtt3h0000gn/T/AppTranslocation/E96CAD52-9C25-4599-93EA-BE8484F2FE24/d/Exchanger.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/private/var/folders/62/3hgy6yr57zz90gmz0w3gtt3h0000gn/T/AppTranslocation/E96CAD52-9C25-4599-93EA-BE8484F2FE24/d/Exchanger.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10d2e5000 -        0x10d2e5ff7 +com.electron.exchanger (1.0.0 - 1.0.0) <F8DFE287-C6B4-3716-B3B3-CDF539205B40> /var/folders/*/Exchanger.app/Contents/MacOS/Exchanger
       0x10fe0f000 -        0x10fe59acf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld
    0x7fff2e33b000 -     0x7fff2e43fffb  com.apple.Bluetooth (6.0.7 - 6.0.7f10) <557F26F9-C7A0-34EA-A905-22E243BF6B48> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

Model: MacBookPro12,1, BootROM MBP121.0177.B00, 2 processors, Intel Core i5, 2.7 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by surfow** [comment]
i'm working on it, it will be fixed soon, **thanks** for reporting

**Comment by surfow** [comment]
Please checkout the new release
